[31-Oct-23 21:18:36 - INFO - init.py:19 - <module>()]  ----------- Starting Up -----------
[31-Oct-23 21:18:36 - INFO - state.py:70 - __init__()]  IP is 169.254.53.33
[31-Oct-23 21:18:36 - INFO - camera.py:21 - __init__()]  Platform is linux
[31-Oct-23 21:18:36 - INFO - camera.py:38 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:18:36 - INFO - camera.py:66 - __init__()]  Supported resolutions: [(160, 120), (176, 144), (320, 240), (352, 288), (416, 240), (424, 240), (640, 360), (640, 480), (800, 448), (800, 600), (960, 544), (1280, 720), (1280, 800)]
[31-Oct-23 21:18:36 - INFO - camera.py:75 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:18:36 - INFO - camera.py:252 - importConfig()]  Attempting to import config for platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:18:36 - WARNING - camera.py:262 - importConfig()]  Config not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:18:36 - INFO - calibration.py:314 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(640, 480)CalData.json
[31-Oct-23 21:18:36 - ERROR - camera.py:245 - importCalibration()]  Calibration not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0 at resolution (640, 480)
[31-Oct-23 21:18:36 - WARNING - camera.py:275 - importConfig()]  Camera config not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:21:25 - INFO - init.py:19 - <module>()]  ----------- Starting Up -----------
[31-Oct-23 21:21:25 - INFO - state.py:151 - setIP()]  Attempting to set static IP
[31-Oct-23 21:21:25 - INFO - state.py:160 - setIP()]  Static IP set: 169.254.53.33 =? 169.254.53.33
[31-Oct-23 21:21:25 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[31-Oct-23 21:21:52 - INFO - init.py:19 - <module>()]  ----------- Starting Up -----------
[31-Oct-23 21:21:52 - INFO - state.py:151 - setIP()]  Attempting to set static IP
[31-Oct-23 21:21:52 - INFO - state.py:160 - setIP()]  Static IP set: 169.254.53.33 =? 169.254.53.33
[31-Oct-23 21:21:52 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[31-Oct-23 21:22:16 - INFO - init.py:19 - <module>()]  ----------- Starting Up -----------
[31-Oct-23 21:22:16 - INFO - state.py:151 - setIP()]  Attempting to set static IP
[31-Oct-23 21:22:16 - INFO - state.py:160 - setIP()]  Static IP set: 169.254.53.33 =? 169.254.53.33
[31-Oct-23 21:22:16 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[31-Oct-23 21:22:16 - INFO - state.py:112 - makePublisher()]  Robot publisher created: 2767 - WallEye
[31-Oct-23 21:22:16 - INFO - camera.py:21 - __init__()]  Platform is linux
[31-Oct-23 21:22:16 - INFO - camera.py:38 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:16 - INFO - camera.py:66 - __init__()]  Supported resolutions: [(160, 120), (176, 144), (320, 240), (352, 288), (416, 240), (424, 240), (640, 360), (640, 480), (800, 448), (800, 600), (960, 544), (1280, 720), (1280, 800)]
[31-Oct-23 21:22:16 - INFO - camera.py:75 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:16 - INFO - camera.py:252 - importConfig()]  Attempting to import config for platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:16 - WARNING - camera.py:262 - importConfig()]  Config not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:16 - INFO - calibration.py:314 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(640, 480)CalData.json
[31-Oct-23 21:22:16 - ERROR - camera.py:245 - importCalibration()]  Calibration not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0 at resolution (640, 480)
[31-Oct-23 21:22:16 - WARNING - camera.py:275 - importConfig()]  Camera config not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:23 - INFO - init.py:19 - <module>()]  ----------- Starting Up -----------
[31-Oct-23 21:22:23 - INFO - state.py:151 - setIP()]  Attempting to set static IP
[31-Oct-23 21:22:23 - INFO - state.py:160 - setIP()]  Static IP set: 169.254.53.33 =? 169.254.53.33
[31-Oct-23 21:22:23 - INFO - state.py:112 - makePublisher()]  Robot publisher created: 2767 - WallEye
[31-Oct-23 21:22:23 - INFO - camera.py:21 - __init__()]  Platform is linux
[31-Oct-23 21:22:23 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[31-Oct-23 21:22:24 - INFO - camera.py:38 - __init__()]  Camera found: platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:24 - INFO - camera.py:66 - __init__()]  Supported resolutions: [(160, 120), (176, 144), (320, 240), (352, 288), (416, 240), (424, 240), (640, 360), (640, 480), (800, 448), (800, 600), (960, 544), (1280, 720), (1280, 800)]
[31-Oct-23 21:22:24 - INFO - camera.py:75 - __init__()]  Auto exposure disabled for platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:24 - INFO - camera.py:252 - importConfig()]  Attempting to import config for platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:24 - WARNING - camera.py:262 - importConfig()]  Config not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0
[31-Oct-23 21:22:24 - INFO - calibration.py:314 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc800000-usb-usb-0-1-1-0-video-index0_(640, 480)CalData.json
[31-Oct-23 21:22:24 - ERROR - camera.py:245 - importCalibration()]  Calibration not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0 at resolution (640, 480)
[31-Oct-23 21:22:24 - WARNING - camera.py:275 - importConfig()]  Camera config not found for camera platform-fc800000.usb-usb-0:1:1.0-video-index0
