[27-Jul-23 19:54:53 - INFO - init.py:13 - <module>()]  ----------- Starting Up -----------
[27-Jul-23 19:54:53 - INFO - camera.py:36 - __init__()]  Platform is linux
[27-Jul-23 19:54:53 - INFO - camera.py:50 - __init__()]  Camera found: platform-xhci-hcd.9.auto-usb-0:1.3:1.0-video-index0
[27-Jul-23 19:54:53 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (160, 120), (176, 144), (176, 144), (320, 240), (320, 240), (352, 288), (352, 288), (416, 240), (424, 240), (640, 360), (640, 360), (640, 480), (640, 480), (800, 448), (800, 448), (800, 600), (800, 600), (960, 544), (960, 544), (1280, 720), (1280, 720), (1280, 800)]
[27-Jul-23 19:54:53 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-xhci-hcd.9.auto-usb-0:1.3:1.0-video-index0
[27-Jul-23 19:54:53 - INFO - camera.py:98 - __init__()]  Config found!
[27-Jul-23 19:54:53 - INFO - calibration.py:286 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-xhci-hcd-9-auto-usb-0-1-3-1-0-video-index0_(640, 480)CalData.json
[27-Jul-23 19:54:53 - WARNING - camera.py:238 - importCalibration()]  Calibration not found for camera platform-xhci-hcd.9.auto-usb-0:1.3:1.0-video-index0 at resolution (640, 480)
[27-Jul-23 19:54:53 - INFO - camera.py:166 - setResolution()]  Resolution set to [640, 480] for platform-xhci-hcd.9.auto-usb-0:1.3:1.0-video-index0
[27-Jul-23 19:54:53 - INFO - camera.py:176 - setGain()]  Gain set to -1.0
[27-Jul-23 19:54:53 - WARNING - camera.py:190 - setExposure()]  Exposure not set: 45.0 not accepted
[27-Jul-23 19:54:53 - INFO - camera.py:50 - __init__()]  Camera found: platform-fc880000.usb-usb-0:1:1.0-video-index0
[27-Jul-23 19:54:53 - INFO - camera.py:77 - __init__()]  Supported resolutions: [(160, 120), (160, 120), (176, 144), (176, 144), (320, 240), (320, 240), (352, 288), (352, 288), (416, 240), (424, 240), (640, 360), (640, 360), (640, 480), (640, 480), (800, 448), (800, 448), (800, 600), (800, 600), (960, 544), (960, 544), (1280, 720), (1280, 720), (1280, 800)]
[27-Jul-23 19:54:53 - INFO - camera.py:83 - __init__()]  Auto exposure disabled for platform-fc880000.usb-usb-0:1:1.0-video-index0
[27-Jul-23 19:54:53 - INFO - camera.py:98 - __init__()]  Config found!
[27-Jul-23 19:54:53 - INFO - calibration.py:286 - parseCalibration()]  Looking for calibration stored at ./Calibration/Cam_platform-fc880000-usb-usb-0-1-1-0-video-index0_(1280, 800)CalData.json
[27-Jul-23 19:54:53 - INFO - camera.py:133 - setCalibration()]  Calibration set for platform-fc880000.usb-usb-0:1:1.0-video-index0, using [[1.02872284e+03 0.00000000e+00 6.55120592e+02]
 [0.00000000e+00 1.04415838e+03 4.48553274e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.19168436 -1.0964342  -0.00910913  0.00238106  0.51537785]]
[27-Jul-23 19:54:53 - INFO - camera.py:233 - importCalibration()]  Calibration found! Using
[[1.02872284e+03 0.00000000e+00 6.55120592e+02]
 [0.00000000e+00 1.04415838e+03 4.48553274e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 0.19168436 -1.0964342  -0.00910913  0.00238106  0.51537785]]
[27-Jul-23 19:54:53 - INFO - camera.py:166 - setResolution()]  Resolution set to [1280, 800] for platform-fc880000.usb-usb-0:1:1.0-video-index0
[27-Jul-23 19:54:53 - INFO - camera.py:176 - setGain()]  Gain set to -1.0
[27-Jul-23 19:54:53 - WARNING - camera.py:190 - setExposure()]  Exposure not set: 156.0 not accepted
[27-Jul-23 19:54:53 - INFO - init.py:40 - <module>()]  Web server ready
[27-Jul-23 19:54:53 - INFO - state.py:91 - makePublisher()]  Robot publisher created: 2767 - Walleye
[27-Jul-23 19:54:53 - INFO - Processing.py:14 - __init__()]  Tag layout loaded
[27-Jul-23 19:54:53 - INFO - NetworkClient.cpp:141 - None()]  starting network client
[27-Jul-23 19:54:53 - INFO - init.py:50 - <module>()]  Starting main loop
