[18-May-24 19:50:28 - INFO - init.py:24 - <module>()]  ----------- Starting Up -----------
[18-May-24 19:50:29 - ERROR - state.py:255 - get_current_ip()]  Could not get current IP - [Errno 19] No such device - Returning None
[18-May-24 19:50:29 - INFO - state.py:88 - __init__()]  IP is None
[18-May-24 19:50:29 - INFO - camera.py:24 - __init__()]  Platform is linux
[18-May-24 19:50:29 - INFO - camera.py:48 - __init__()]  Camera found: pci-0000:04:00.0-usbv2-0:1:1.0-video-index0
[18-May-24 19:50:29 - INFO - camera.py:59 - __init__()]  Supported resolutions: [(640, 360), (640, 480)]
[18-May-24 19:50:29 - INFO - camera.py:62 - __init__()]  Supported formats: ['Motion-JPEG', 'YUYV 4:2:2']
[18-May-24 19:50:29 - INFO - camera.py:65 - __init__()]  Supported exposures (min, max, step): (10, 2500, 1)
[18-May-24 19:50:29 - INFO - camera.py:68 - __init__()]  Supported brightnesses (min, max, step): (-64, 64, 1)
[18-May-24 19:50:29 - INFO - camera.py:77 - __init__()]  Auto exposure disabled for pci-0000:04:00.0-usbv2-0:1:1.0-video-index0
[18-May-24 19:50:29 - INFO - camera.py:312 - import_config()]  Attempting to import config for pci-0000:04:00.0-usbv2-0:1:1.0-video-index0
[18-May-24 19:50:29 - WARNING - camera.py:321 - import_config()]  Config not found for camera pci-0000:04:00.0-usbv2-0:1:1.0-video-index0
[18-May-24 19:50:29 - INFO - calibration.py:422 - parse_calibration()]  Looking for calibration stored at walleye-data/config_data/calibrations/cam_pci-0000-04-00-0-usbv2-0-1-1-0-video-index0_(640, 480)_cal_data.json
[18-May-24 19:50:29 - ERROR - camera.py:303 - import_calibration()]  Calibration not found for camera pci-0000:04:00.0-usbv2-0:1:1.0-video-index0 at resolution (640, 480)
[18-May-24 19:50:29 - WARNING - camera.py:334 - import_config()]  Camera config not found for camera pci-0000:04:00.0-usbv2-0:1:1.0-video-index0
[18-May-24 19:50:29 - WARNING - camera.py:95 - __init__()]  Failed to open camera: pci-0000:04:00.0-usb-0:1:1.0-video-index1
[18-May-24 19:50:29 - WARNING - camera.py:95 - __init__()]  Failed to open camera: pci-0000:04:00.0-usb-0:1:1.0-video-index0
[18-May-24 19:50:29 - WARNING - camera.py:95 - __init__()]  Failed to open camera: pci-0000:04:00.0-usbv2-0:1:1.0-video-index1
[18-May-24 19:50:30 - INFO - image_streams.py:48 - __init__()]  Tag layout loaded
[18-May-24 19:50:32 - INFO - init.py:66 - <module>()]  Web server ready
[18-May-24 19:50:32 - INFO - processing.py:20 - __init__()]  Tag layout loaded
[18-May-24 19:50:32 - INFO - init.py:77 - <module>()]  Starting main loop
[18-May-24 19:50:32 - CRITICAL - init.py:259 - <module>()]  'NoneType' object has no attribute 'get_time'
Traceback (most recent call last):
  File "/home/dshen/Code/wallEYE/PiSideCode/init.py", line 197, in <module>
    image_time = walleye_data.robot_publisher.get_time()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_time'
[18-May-24 19:50:32 - INFO - init.py:260 - <module>()]  Shutting down
